services:
  spark-master:
    image: apache/spark:3.4.1
    pull_policy: never
    container_name: egx-spark-master
    hostname: spark-master
    restart: unless-stopped
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      HADOOP_CONF_DIR: /opt/spark/conf/hadoop
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ../../:/opt/spark/apps
      - ../../config/hadoop:/opt/spark/conf/hadoop
    networks:
      - egx-network

  spark-worker:
    image: apache/spark:3.4.1
    pull_policy: never
    container_name: egx-spark-worker
    hostname: spark-worker
    restart: unless-stopped
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
      HADOOP_CONF_DIR: /opt/spark/conf/hadoop
    ports:
      - "8081:8081"
    volumes:
      - ../../:/opt/spark/apps
      - ../../config/hadoop:/opt/spark/conf/hadoop
    networks:
      - egx-network
