services:
  spark-master:
    image: apache/spark:3.4.1
    pull_policy: never
    container_name: egx-spark-master
    hostname: spark-master
    restart: unless-stopped
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - spark-apps:/opt/spark/apps
    networks:
      - egx-network

  spark-worker:
    image: apache/spark:3.4.1
    pull_policy: never
    container_name: egx-spark-worker
    hostname: spark-worker
    restart: unless-stopped
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
    ports:
      - "8081:8081"
    volumes:
      - spark-apps:/opt/spark/apps
    networks:
      - egx-network

volumes:
  spark-apps:
