name: egx-bigdata-pipeline

include:
  - path: ./hadoop/docker-compose.yml
  - path: ./hive/docker-compose.yml
  - path: ./kafka/docker-compose.yml
  - path: ./spark/docker-compose.yml
  - path: ./airflow/docker-compose.yml

networks:
  egx-network:
    name: egx-network
    driver: bridge
